version: 1.7.2.{build}

platform: Any CPU

configuration: Release

before_build:
  - nuget restore upScreen\upScreen.sln

after_build:
  - ps: .\pack.ps1

build:
  project: upScreen\upScreen.sln
  verbosity: normal

artifacts:
  - path: 'Releases\*.exe'
    name: Setup
  - path: 'Releases\RELEASES'
    name: Releases
  - path: 'Releases\*.nupkg'
    name: NugetPackage