version: 1.7.1.{build}

platform: Any CPU

configuration: Release

before_build:
  - nuget restore upScreen\upScreen.sln

build:
  project: upScreen\upScreen.sln
  verbosity: normal

artifacts:
  - path: 'bin\Release\Releases\*.exe'
    name: Setup
  - path: 'bin\Release\Releases\RELEASES'
    name: Releases
  - path: 'bin\Release\Releases\*.nupkg'
    name: NugetPackage